apiVersion: v1
kind: Namespace
metadata:
  name: externaldb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: externaldb
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: docker.io/giriraj789/voteweb:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "300m"
          ports:
          - containerPort: 8080
          env:
          - name: DB_NAME
            value: vote_db
          - name: DB_PASSWD
            value: india@123
          - name: DB_USER
            value: root
          - name: DB_ADDR
            value: externaldb
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: externaldb
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 32301
---
apiVersion: v1
kind: Service
metadata:
  name: externaldb
spec:
  selector:
    app: externaldb
  ports:
    - name: externaldb
      protocol: TCP
      port: 3306
      targetPort: 3306
  externalIPs:
    - 15.206.49.8
