apiVersion: apps/v1
kind: Deployment
metadata:
  name: logtest
  labels:
    logtest: logtest
spec:
  replicas: 1
  selector:
    matchLabels:
      logtest: logtest
  template:
    metadata:
      labels:
        logtest: logtest
    spec:
      containers:
      - name: logtest
        image: docker.io/giriraj789/logtest:v1
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "300m"

