apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "200m"
      memory: "200Mi"
    min:
      cpu: "100m"
      memory: "99Mi"
    default:
      cpu: "150m"
      memory: "150Mi"
    defaultRequest:
      cpu: "100m"
      memory: "100Mi"
    type: Container
