--- 
apiVersion: apps/v1beta2
kind: Deployment
metadata: 
  name: veg
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: veg
  template: 
    metadata: 
      labels: 
        app: veg
    spec: 
      containers: 
        - 
          image: "docker.io/giriraj789/demopod:v1"
          name: veg
      tolerations: 
        - 
          key: color
          operator: Equal
          value: green

