--- 
apiVersion: apps/v1beta2
kind: Deployment
metadata: 
  name: nonveg
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nonveg
  template: 
    metadata: 
      labels: 
        app: nonveg
    spec: 
      containers: 
        - 
          image: "docker.io/giriraj789/demopod:v1"
          name: nonveg
      tolerations: 
        - 
          key: color
          operator: Equal
          value: red

