apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airroutepvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: airroute
