---
apiVersion: v1
kind: Service
metadata:
  name: promnp
spec:
  type: NodePort
  ports:
    - port: 9113
      protocol: TCP
      targetPort: 9113
      nodePort: 30911
  selector:
    app: my-release-nginx-ingress

