
STEPS
-----

$git clone https://github.com/k8snetworkplumbingwg/multus-cni.git && cd multus-cni
$cat ./deployments/multus-daemonset-thick.yml | kubectl apply -f -
$ touch NAD.yaml, contents are below , Also choose "master": "enp0s8" as your ethernet interface. 

--------
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp0s8",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.1.1.0/24",
        "rangeStart": "10.1.1.50",
        "rangeEnd": "10.1.1.70",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.1.1.1"
      }
    }'
  EOF
  -----------
  Verfication
  -----------
$kubectl get network-attachment-definitions
$kubectl get crd
$kubectl describe network-attachment-definitions macvlan-conf
$ip link show
$kubectl create -f https://raw.githubusercontent.com/learnbyseven/SERVICEMESH/main/kube-apps/netcat_pod_multus.yaml
$kubectl exec -it nc1 -- /bin/bash
---------
PS : NetworkAttachmentDefinition needs to be created withing the namespace for NS pods to use it.

    
