apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  ports:
  - port: 8080
    name: webserver
  clusterIP: None
  selector:
    app: webserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver # has to match .spec.template.metadata.labels
  serviceName: "webserver"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: webserver # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: webserver
        image: docker.io/giriraj789/apache:v1
        ports:
        - containerPort: 8080
          name: webserver
