apiVersion: v1
kind: Service
metadata:
  name: headless
  labels:
    app: headless
spec:
  ports:
  - port: 8080
    name: headless
  clusterIP: None
  selector:
    app: headless
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: headless
spec:
  selector:
    matchLabels:
      app: headless # has to match .spec.template.metadata.labels
  serviceName: "headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: headless # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: headless
        image: docker.io/giriraj789/webserver
        ports:
        - containerPort: 8080
          name: headless
