--- 
apiVersion: v1
kind: Pod
metadata: 
  name: webserver
spec: 
  containers: 
    - 
      image: "docker.io/giriraj789/blue:v1"
      name: webservera
      ports: 
        - 
          containerPort: 8080
