apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime
  namespace: runtime
  labels:
    app: runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runtime
  template:
    metadata:
      labels:
        app: runtime
    spec:
      containers:
      - name: runtime
        image: docker.io/giriraj789/webdev:v1
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "300m"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: runtime
  namespace: runtime
spec:
  selector:
    app: runtime
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      nodePort: 32400
      
